name: Build and Publish Docker Image in Github Registry

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # # Step 2: Log in to GitHub Container Registry
    # - name: Log in to GitHub Container Registry
    #   run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.TOKEN }}

    # Step 3: Build Docker image
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.actor }}/learning-github-cotainer-registry-api:latest .

    # Step 4: Push Docker image to GitHub Container Registry
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.actor }}/learning-github-cotainer-registry-api:latest
